source 'https://github.com/CocoaPods/Specs.git'

target 'A0Keychain', :exclusive => true do
  pod "A0Keychain", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "A0Keychain", :path => "../"

  pod 'Specta', '~> 0.2.1', :inhibit_warnings => true
  pod 'Expecta'
end
