version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.2.0"

    steps:
      - checkout
      - run: | 
          bundle install --without=development
      - run:
          name: Bootstrap
          command: bundle exec fastlane ios bootstrap
      - run:
          name: Run test suite
          command: bundle exec fastlane ios ci
          environment:
            SCHEME: SimpleKeychain-iOS
            DEVICE: iPhone 8
            FASTLANE_EXPLICIT_OPEN_SIMULATOR: 2
      - run:
          name: Pod Lib Lint
          command: bundle exec fastlane ios pod_lint
      - run:
          name: SwiftPM Test
          command: swift test
      - run: |
          bash <(curl -s https://codecov.io/bash) -J 'SimpleKeychain' 
      - save_cache:
          key: dependency-cache
          paths:
            - Carthage/Build
      - store_test_results:
          path: fastlane/test_output

workflows:
  version: 2
  build-test-report:
    jobs:
      - build-and-test