source 'https://github.com/CocoaPods/Specs.git'

target 'A0SimpleKeychainOSX', :exclusive => true do
  pod "SimpleKeychain", :path => "../../"
end

target 'A0SimpleKeychainOSXTests', :exclusive => true do
  pod "SimpleKeychain", :path => "../../"

  pod 'Specta', '~> 0.2.1', :inhibit_warnings => true
  pod 'Expecta'
end
