#!/bin/bash

echo ""
echo "####### Bootstrap Phase #######"
echo ""
NO_CARTHAGE_UPDATE=true script/bootstrap
status=$?

if [ $status -eq 0 ]
then
  echo ""
  echo ""
  echo "####### Build & Test Phase #######"
  echo ""
  set -o pipefail && script/test 2>&1 | tee /tmp/build.test-output.txt
  status=$?
  if [ ! $status -eq 0 ]
  then
    log_file_path=`cat /tmp/build.test-output.txt | tail -n 100 | perl -l -ne '/(\/var\/folders.*\/com\.apple\.dt\.XCTest-status.*)\)/ && print $1'`
    if [ ! -z "$log_file_path" ]
    then
      echo ""
      echo " → The tests have failed. Printing output of log file '$log_file_path'."
      cat $log_file_path
      echo ""
    fi
  fi
fi

exit $status
